### ISSUE TITLE
Way to tell what version is running?

### ISSUE THREAD

**Issue by stevecj** [ringcentral/ringcentral-community-app#15]
I installed the latest and wanted to be able to tell whether that worked correctly so that I am now running the latest version. There's no obvious way to tell.

The best that I was able to do is search the Web to learn that I can read the /usr/share/applications/ringcentral-community-app.desktop file to find the name of the executable, then check the date of the "/opt/RingCentral (Community) app/ringcentral-community-app" file to see that it is from close to the latest release date.

For now, maybe just add the version number to the title bar text to keep it simple (even though slightly messy) and then, at some time in the future, add a hamburger menu on the title bar that includes "About".

**Comment by embbnux** [comment]
Thanks @stevecj It is good idea to add "About". Added it into backlog.

**Comment by embbnux** [comment]
supported at 0.0.5
