### ISSUE TITLE
Cannot download files on ArchLinux

### ISSUE THREAD

**Issue by l-alfred** [ringcentral/ringcentral-community-app#16]
I have made a local `PKGBUILD` file to install the app on a ArchLinux based distribution. The app seems to work fine, apart from one thing. I cannot download files shared on the chat. Although, I can open a `.pdf` by clicking on its name, I cannot download it by clicking on the download icon.

I am not familiar with electron apps, so I don't know if it is related to a missing dependency on the OS side or a missing functionality on the app side.

By the way, if wanted, I can share the `PKGBUILD` file.

**Comment by embbnux** [comment]
Hi @l-alfred, thanks for reporting this. I can reproduce in my side with Ubuntu. Let me find how to fix this.

**Comment by embbnux** [comment]
hi @l-alfred I merged a PR into master to support download from app.
Can you help to rebuild in ArchLinux to try it? You need to pull latest code and install dependency by yarn.

A known issue is that user can't download pdf from preview page. Only download pdf with download button at conversation page

**Comment by l-alfred** [comment]
Hi @embbnux, I have built the new version on ArchLinux and the app is now able to download any file. Thanks for the quick fix!

**Comment by embbnux** [comment]
Great! Thanks for checking at ArchLinux.
