### ISSUE TITLE
Add an option to increase or reduce the font size

### ISSUE THREAD

**Issue by l-alfred** [ringcentral/ringcentral-community-app#17]
I was looking for a way to increase the font size in the app, and I have noticed that there is no option to do so. I think it is the same for the web app, there is no accessibility option unfortunately. 

I guess, one solution could be to add a zoom in/out functionality from the electron engine (e.g., CTRL+scroll up/down).
Thanks for taking the time to look into it!

**Comment by embbnux** [comment]
Hi @l-alfred yes, I think it can be done by setting zoom https://www.electronjs.org/docs/latest/api/web-frame
And can you help to share why you need this feature?

**Comment by l-alfred** [comment]
Hi @embbnux, some colleagues find the default font size too small for them, in a sense that they need to come closer to the screen to read the chat messages. Having the ability to zoom in could make the experience more enjoyable for them.

**Comment by embbnux** [comment]
> Hi @embbnux, some colleagues find the default font size too small for them, in a sense that they need to come closer to the screen to read the chat messages. Having the ability to zoom in could make the experience more enjoyable for them.

Thanks for explaining it. Let me discuss with team about how to support this.

**Comment by embbnux** [comment]
supported with https://github.com/ringcentral/ringcentral-community-app/pull/25
