### ISSUE TITLE
Failed to run `yarn package-linux` with Node.js >= 16

### ISSUE THREAD

**Issue by VGuenat** [ringcentral/ringcentral-community-app#20]
First of all, thank you for the package, it's really great!

I am using ArchLinux with Node.js version 17.3.0 and I noticed the same problem as described here: https://github.com/electron-userland/electron-builder/issues/5668 i.e. that the `yarn package-linux` command fails. Running `yarn upgrade` before that solves the issue by bumping `electron-builder` to version `22.14.5`.

Could it be possible to already bump the `electron-builder` version in the repo, or at least add a mention in the README.md?

**Comment by embbnux** [comment]
Thanks so much for feedback @VGuenat. It is updated now

**Comment by VGuenat** [comment]
Thank you for the quick fix, it is solved now. Closing.
