### ISSUE TITLE
Add the possibility to change the spell checker language

### ISSUE THREAD

**Issue by l-alfred** [ringcentral/ringcentral-community-app#23]
**Context:** I work in a multicultural company and sometime we write messages in different languages (for ex., person A talks to person B in English and A talks to C in Spanish).

**Idea:** Being able to easily change the spell checker language while writing messages. For example:

- right-clicking on the message box and selecting another language,
- or assigning a language per direct messages group.

By the way: the app is now on the ArchLinux AUR: https://aur.archlinux.org/packages/ringcentral-community-app-git

**Comment by embbnux** [comment]
supported at 0.0.6. User can right click at input area to get spell checker lang settings
