### ISSUE TITLE
Captures Ctrl+O key combination system-wide!

### ISSUE THREAD

**Issue by stevecj** [ringcentral/ringcentral-community-app#28]
It took me a while to figure out why the Ctrl+O key combination was no longer working in any of the Gnome apps on my system. I finally figured out that it stops working after I start the RC app and starts working again as soon as I close the RC app.

Since I use Ctrl+O quite a lot in Vim, this is very inconvenient for me.

**Comment by embbnux** [comment]
Hi @stevecj sorry about this. I have removed non-standard shortcut in #29. will release 0.0.6 to fix this.

**Comment by embbnux** [comment]
fixed at 0.0.6
