### ISSUE TITLE
What are the goals of this application? Perhaps, add to README

### ISSUE THREAD

**Issue by stevecj** [ringcentral/ringcentral-community-app#3]
What is this app trying to achieve? Is it just to have RC run as it normally would within a browser window or tab but in a separately named application? If so, then I think that does have some value just in terms of being able to find the window.

In any case, it would be good to know what benefits this app is supposed to provide.

**Comment by embbnux** [comment]
Thanks @stevecj The app is still in early step. It is mostly for building RingCentral desktop for linux users. Updated README..

**Comment by embbnux** [comment]
close this by inactive. Feel free to reopen it.
