### ISSUE TITLE
JavaScript ERR_INVALID_URL on Start Video Meeting

### ISSUE THREAD

**Issue by mreschke** [ringcentral/ringcentral-community-app#37]
On manjaro, yay -S ringcentral-community-app-git which brings in ringcentral-community-app-git 0.0.7.r0.gdd3c878-1

App install fine, electron app opens fine.  Messaging works fine.

Click on Video->Meetings.  Start new meeting, either with rendom meeing ID or my personal meeting ID and I always get this JavsScript Error.

![image](https://user-images.githubusercontent.com/4038770/191574181-85c1071b-4a49-4afe-be1d-f84f88ef731f.png)

**Comment by mreschke** [comment]
In the mean time...for those of you on non Debian/Ubuntu Linux OS's where you also get the JS error.  You can simply run this in chrome or chromiums "app" mode. 
```
chromium --app=https://app.ringcentral.com/video/home
```
No electron or other apps required.  New "Video Meetings" seem to work as well.

**Comment by embbnux** [comment]
Thanks @mreschke for feedback. Let me check this.

**Comment by embbnux** [comment]
Hi @mreschke we release [0.0.8](https://github.com/ringcentral/ringcentral-community-app/releases/tag/v0.0.8) to fix this. Can you help to check if this work at your side

**Comment by mreschke** [comment]
Hey hey, you fixed it @embbnux.  Even had it updated on Arch AUR!!!  Ran yay -S ringcentral-community-app again which pulled in ringcentral-community-app-git 0.0.8.r0.gffaef18-1 instead of older ringcentral-community-app-git 0.0.4.r3.g751b79b-1 and I can start and join meetings now!  Thanks for the quick turn around!

**Comment by embbnux** [comment]
Great thanks @mreschke for confirming!
