### ISSUE TITLE
Unable to join video meetings

### ISSUE THREAD

**Issue by Graeme-Parker-Smith** [ringcentral/ringcentral-community-app#40]
Whenever I try to join a meeting the app redirects me to a browser page like the one pictured below. But even after signing in or clicking "join as attendee" on the browser, I still can't join meetings using the community app. Is the community app supposed to be capable of joining meetings created from the official app, or is opening meetings in the browser my only option?

![Screenshot from 2022-11-26 17-41-55](https://user-images.githubusercontent.com/54484870/204113162-ffe3f636-1a5a-42f0-b4fb-133fb80156ee.png)

**Comment by embbnux** [comment]
Hi @Graeme-Parker-Smith Do you use RingCentral Meetings? Currently the community app only support RingCentral Video.
For RingCentral Meetings, you can use linux client from here https://support.ringcentral.com/article/Meetings-Install-Uninstall-Linux.html

**Comment by Graeme-Parker-Smith** [comment]
I do have the Linux client for Ringcentral Meetings, and I'm able to use that for joining video meetings, but doing so requires me to copy/paste meeting links from either the browser app or the community-app. I was hoping to get a desktop app experience similar to what's available on the Windows and Mac versions (I'm not sure if that's what's meant by "Ringcentral Video". The app downloads page seems to only refer to this as "Ringcentral App").

So far the Community App has been useful and mostly matches the experience of the Windows and Mac Desktop Apps, except when attempting to join a meeting. Doing that will present an error message in the community app. I'm running Linux Mint 21 Cinnamon, if that matters.
![2022-11-27 20_56_22-Window](https://user-images.githubusercontent.com/54484870/204183033-33c8bef1-a7e6-4fa3-aa72-24caf6f22756.png)

**Comment by embbnux** [comment]
Hi @Graeme-Parker-Smith  RingCentral provides two video service "RingCentral Video" and "RingCentral Meetings" now.  You can upgrade Video service into RingCentral Video by following this https://support.ringcentral.com/transition-to-rcv/users.html.
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/7036536/204185575-6bfcce7d-c8b4-491f-a3f8-cc3fdbce5d67.png">
The official RingCentral App support both two video service. But it only support Windows and Mac.   
For this project, we are building a community version for RingCentral App to support linux. And currently the community app only supports RingCentral Video service opened in desktop directly. For RingCentral Meetings service, it will open the meeting link in default browser.  And when user click "Join Meeting as attendee", browser should popup dialog for open link in Meetings app:
![image](https://user-images.githubusercontent.com/7036536/204199466-8556a89d-74e0-486f-aed3-2ee0634c1208.png)
I tested in my Ubuntu, only Firefox supports open link for other apps.

**Comment by Graeme-Parker-Smith** [comment]
@embbnux That makes sense. It appears most of my meetings are through the Ringcentral Meetings service, but I'm able to open those in the Meetings app after setting Firefox as my default browser. Thanks for the detailed and quick response!
