### ISSUE TITLE
Mandatory Software Update???

### ISSUE THREAD

**Issue by titaniumtux** [ringcentral/ringcentral-community-app#42]
I got notified in the app that there's a required update, and that the version I'm using will stop working in 15 days. I don't see any newer version of the RingCentral Community desktop app. I've been using it for video calls. Any fix for this?

**Comment by embbnux** [comment]
Thanks @titaniumtux for feedback. Can you share your OS name and version? When I tested with Ubuntu 22.04, I didn't get the notification. And  any screenshots are appreciated.

**Comment by embbnux** [comment]
From Glip message with @titaniumtux the notification disappeared. For users get the issue, please try the 0.0.9 version.
